steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/clientbackend-297422/clientbackend:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'gcr.io/clientbackend-297422/clientbackend:$SHORT_SHA']
